### ISSUE TITLE
Not a real issue

### ISSUE THREAD

**Issue by andreaskaris** [justinrdonnelly/wandering-pixel#1]
Not a real issue. I just wanted to say thank you! I used to open cairo-clock every time that I had to work with Terminator. This seems to be a way better workaround. A really simple implementation, yet a brilliant idea!

**Comment by daniel5151** [comment]
Not a real comment. I also wanted to say thanks! I've been using glxgears as a workaround for months now, so I can't tell you how excited I am to once again reclaim that corner of my monitor :smile:

**Comment by dimisjim** [comment]
thank you!!!

**Comment by justinrdonnelly** [comment]
Thanks so much for all the feedback! I'm glad people find it useful.

**Comment by zpetukhov** [comment]
This seems fixed my issue with sublime text freezing.
Thank you very much!

**Comment by jansalleine** [comment]
Awesome!
Fixes Geany ( https://github.com/geany/geany/issues/2658 ) and terminal freezing for me.
Thank you!!!

**Comment by justinrdonnelly** [comment]
It's probably time to close this feel-good issue. Thanks again for all the positive feedback!
