### ISSUE TITLE
Add extension to Gnome Extensions

### ISSUE THREAD

**Issue by DragosMocrii** [justinrdonnelly/wandering-pixel#2]
Would you mind adding your extension to https://extensions.gnome.org/ ? It would make it easier for others to install it.

And yes, it worked :) Props to you for the effort and creativity 👍

**Comment by justinrdonnelly** [comment]
That seems like a good idea. Besides being easier, it should also give users some piece of mind from a security perspective. I'll try to get to it soon.

**Comment by justinrdonnelly** [comment]
It's now available: https://extensions.gnome.org/extension/4028/wandering-pixel/
