### ISSUE TITLE
Why not 2 pixels apposing each other

### ISSUE THREAD

**Issue by fawtytoo** [justinrdonnelly/wandering-pixel#3]
The pixel takes 1 minute to cover the entire width, so you could be waiting a while for a part of the screen to redraw.
So, why not 2 pixels either end. That would cover the distance twice as fast.

Just a thought.

**Comment by justinrdonnelly** [comment]
From my testing it doesn't matter where the pixel is on the screen. Just by some part of the screen changing, it forces the screen to redraw. Are you finding that's not the behavior you're seeing?
